version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: ticketing_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: postgres
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      DB_NAME: ticketing_db
    depends_on:
      - postgres
    ports:
      - "5000:5000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"

volumes:
  pgdata: